<?php

namespace ContainerZmwvmOD;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_JJPnaaOService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.JJPnaaO' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.JJPnaaO'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'hashedPassword' => ['privates', 'security.user_password_hasher', 'getSecurity_UserPasswordHasherService', true],
            'users' => ['privates', 'App\\Repository\\UserRepository', 'getUserRepositoryService', true],
        ], [
            'hashedPassword' => '?',
            'users' => 'App\\Repository\\UserRepository',
        ]);
    }
}
