<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerVOVB2HH\App_KernelProdContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerVOVB2HH/App_KernelProdContainer.php') {
    touch(__DIR__.'/ContainerVOVB2HH.legacy');

    return;
}

if (!\class_exists(App_KernelProdContainer::class, false)) {
    \class_alias(\ContainerVOVB2HH\App_KernelProdContainer::class, App_KernelProdContainer::class, false);
}

return new \ContainerVOVB2HH\App_KernelProdContainer([
    'container.build_hash' => 'VOVB2HH',
    'container.build_id' => '4ddc3449',
    'container.build_time' => 1651157710,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerVOVB2HH');
